name: Deploy on dev server

on:
  push:
    branches:
      - main

jobs:
  redeploy:
    name: Deploy everything to the dev server
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
          chmod 600 ssh_key
      
      - name: SSH to the server 
        run: ssh -i ssh_key ubuntu@13.222.133.210
      
      -name: show all files
        run: ls
          